# NumPy Library
* NumPy is an open source and free python library for math and computation
* Large number of functions to work with n-dimensional arrays
* NumPy: Numerical Python
* Importing: import numpy as np

In [1]:
import numpy as np

In [4]:
# create an array from the numpy library
x = np.array([1, 2, 3, 4])

In [5]:
x

array([1, 2, 3, 4])

In [7]:
print(x)

[1 2 3 4]


In [9]:
# creating array of zeros
np.zeros(5)

[0. 0. 0. 0. 0.]


In [10]:
# creating array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
# displaying random numbers
# from 0 to 1
np.random.random(5)

array([0.44817385, 0.37739718, 0.61393875, 0.36916788, 0.14017822])

# NumPy 1-D Operations
* Do math operations for 1-D arrays with NumPy

In [13]:
var_array1 = np.array([1, 2, 3])

In [15]:
var_array2 = np.ones(3)

In [17]:
# Addition of items in an array
var_array1 + var_array2 

array([2., 3., 4.])

In [18]:
# Muiltiplication o
var_array1 * 2

array([2, 4, 6])

In [19]:
var_array2 * 3

array([3., 3., 3.])

In [20]:
# Accessing array elements...
var_array1[0]

1

In [21]:
var_array1[1]

2

In [22]:
# use a loop to display all the elements..
for num in var_array1:
    print(num)

1
2
3


In [23]:
for i in range(0, len(var_array2)):
    print(var_array2[i])

1.0
1.0
1.0


# Math Functions with 1-D Array

In [24]:
var_array1.max()

3

In [25]:
var_array1.min()

1

In [26]:
var_array2.sum()

3.0

# Creating N-D Arrrays or Matrices

In [27]:
nd_array = np.array([
    [10, 20],
    [30, 40]
])

In [28]:
nd_array

array([[10, 20],
       [30, 40]])

In [29]:
print(nd_array)

[[10 20]
 [30 40]]


In [30]:
# 2D Array of ones
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
# 2D Array of zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
# 2D Array of random numbers between 0 and 1
np.random.random((3, 4))

array([[0.9320873 , 0.44850216, 0.57995622, 0.68145757],
       [0.69208599, 0.03218298, 0.24603388, 0.20083485],
       [0.88250474, 0.31978514, 0.44814733, 0.71160937]])

# Math with N-D Arrays

In [39]:
y = np.array([
    [2, 4],
    [5, 6]
])

In [41]:
x = np.array([
    [10, 11],
    [25, 30]
])

In [42]:
# Addition...
x + y

array([[12, 15],
       [30, 36]])

In [43]:
x * y

array([[ 20,  44],
       [125, 180]])

In [44]:
# The dot product...
x.dot(y)

array([[ 75, 106],
       [200, 280]])

In [46]:
y.max()

6

In [47]:
y.min()

2

In [48]:
y.sum()

17

# Indexing for Matrices
* Accessing value: <b>arrayName[row, column]</b>

In [52]:
y[0, 1]

4

In [53]:
x[1, 1]

30

In [54]:
x[1, 0]

25

In [55]:
# Accessing may items
y[0:2, 1]

array([4, 6])

# Reshaping Arrays

In [56]:
data = np.array([1, 2, 3, 4, 5, 6])

In [57]:
# reshap data 1-D array to 2-D array
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
data.reshape(2, 4) # take note...

ValueError: cannot reshape array of size 6 into shape (2,4)

In [60]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
# Creating Multi-dimensional Arrays...

x = np.array([
    [
        [10, 20],
        [30, 40],
        [50, 60]
    ],
    [
        [70, 80],
        [90, 100],
        [120, 130]
    ]
])

In [63]:
type(x)

numpy.ndarray

In [64]:
x

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [120, 130]]])

In [65]:
print(x)

[[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[ 70  80]
  [ 90 100]
  [120 130]]]


In [68]:
# 3D array of ones
ones = np.ones((5, 3, 4))

In [69]:
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [72]:
zeros = np.zeros((5, 3, 4))

In [73]:
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [75]:
list(zeros)

[array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])]

In [76]:
type(list(zeros))

list