
# Numpy


In [1]:
# imports 
import numpy as np

## 1D Array 

In [2]:
oneD_array = np.array( [1, 2, 3, 4, 5] )
print( oneD_array )

[1 2 3 4 5]


In [3]:
# check the number of dimensions

print( oneD_array.ndim ) 

1


## 2D Array

In [4]:
# creating a 2D array
# you pass a 2D list or tuple as an argument to the array fxn
# a 2D list is a list in which every element is a 1D list

twoD_array = np.array( [ [1, 2, 3,], [4, 5, 6] ] )
print( twoD_array )

[[1 2 3]
 [4 5 6]]


## 3D Array

In [5]:
# check the number of dimensions

print( twoD_array.ndim )

2


In [6]:
# creating a 3D array
# using a 3D python list or tuple as argument
# a 3D list is where each element of the outermost array is a 2D list

threeD_array = np.array(
    [ # 3D
        [ # 2D
            [1, 2, 3, 4], # 1D
            [-5, -6, -7, -8],
            [9, 10, 11, 12],
            [13, 14, 15, 15]
        ]
    ]
)

print( threeD_array )

[[[ 1  2  3  4]
  [-5 -6 -7 -8]
  [ 9 10 11 12]
  [13 14 15 15]]]


In [7]:
# check the dimension 

print( threeD_array.ndim )

3


## Indexing NumPy Arrays

In [8]:
# display values in an array
# e.g to display 6 from the 2D array: 

twoD_array[1][2]

6

In [9]:
# for 3D -- displaying 11
threeD_array[0][2][2]

11

In [10]:
# for 3D -- displaying 11 method 2
threeD_array[0, 2, 2]

11

## Array Shape

In [11]:
# checking the shape of an array
# shape returns a tuple in which the first value = number of dimensions
# in an array and the second value or third... = number of items 
# in that nd array

print( threeD_array.shape )

(1, 4, 4)


## Iterating Over numPy Arrays

In [12]:
# iterating over a 1D array
# O(n)

for item in oneD_array:
    print( item )

1
2
3
4
5


In [13]:
# iterating over a 2D array
# O(n^2)
for row in twoD_array:
    for value in row:
        print(value)

1
2
3
4
5
6


In [14]:
# iterating over a 3D array
# O (n^3)

for two_D_array in threeD_array:
    for one_D_array in two_D_array:
        for value in one_D_array:
            print( value )

1
2
3
4
-5
-6
-7
-8
9
10
11
12
13
14
15
15


# Math for Data Science

## Array of Zeros

In [15]:
# creating a 1D zeros array of length 10

zeros_array = np.zeros(10)
print( zeros_array )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
# convert zeros_array to int

zeros_array = zeros_array.astype(int)
print( zeros_array )

[0 0 0 0 0 0 0 0 0 0]


## Array of Ones

In [17]:
# creating a 1D ones array of length 10

ones_array = np.ones(10)
print( ones_array )

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
# convert ones_array to int

ones_array = ones_array.astype(int)
print( ones_array )

[1 1 1 1 1 1 1 1 1 1]


## Array with pre-filled values

In [19]:
# creating a array with prefilled values
# first argument is the size of the array
# second argument is the number(s) to fill in the array

prefilled_array = np.full(10, 7)
print( prefilled_array )

[7 7 7 7 7 7 7 7 7 7]


## Scalar Operations

In [20]:
# addition

print( two_D_array )

two_D_array = two_D_array + 2 # add 2 to each element
print()

print( two_D_array )

[[ 1  2  3  4]
 [-5 -6 -7 -8]
 [ 9 10 11 12]
 [13 14 15 15]]

[[ 3  4  5  6]
 [-3 -4 -5 -6]
 [11 12 13 14]
 [15 16 17 17]]


In [21]:
# note addition operation on a list results in an error 

one_D_list = [1, 2, 3, 4]
one_D_list = one_D_list + 2

print( one_D_list )

TypeError: can only concatenate list (not "int") to list

In [22]:
# subtraction

print( two_D_array )

two_D_array = two_D_array - 2
print()

print( two_D_array )

[[ 3  4  5  6]
 [-3 -4 -5 -6]
 [11 12 13 14]
 [15 16 17 17]]

[[ 1  2  3  4]
 [-5 -6 -7 -8]
 [ 9 10 11 12]
 [13 14 15 15]]


In [23]:
# note subtraction operation on a list results in an error 

one_D_list = one_D_list - 2

print( one_D_list )

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [24]:
# multiplication

print( two_D_array )

two_D_array = two_D_array * 2
print()

print(two_D_array)

[[ 1  2  3  4]
 [-5 -6 -7 -8]
 [ 9 10 11 12]
 [13 14 15 15]]

[[  2   4   6   8]
 [-10 -12 -14 -16]
 [ 18  20  22  24]
 [ 26  28  30  30]]


In [25]:
# note multiplication operation on a list results in concatenation
# of a list with itself

one_D_list = one_D_list * 2

print( one_D_list )

[1, 2, 3, 4, 1, 2, 3, 4]


In [26]:
# division (/ --> float or // --> integer)
print( two_D_array )

two_D_array = two_D_array / 2 
print()

print( two_D_array )

[[  2   4   6   8]
 [-10 -12 -14 -16]
 [ 18  20  22  24]
 [ 26  28  30  30]]

[[ 1.  2.  3.  4.]
 [-5. -6. -7. -8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 15.]]


In [27]:
# note division operation on a list results in an error 

one_D_list = one_D_list / 2

print( one_D_list )


TypeError: unsupported operand type(s) for /: 'list' and 'int'

## Transpose Operation

In [29]:
# taking transpose of an array

print( twoD_array )
print()

print( twoD_array.T ) # transpose twoD_array

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


## Element-wise Operations

In [35]:
 # we first create two arrays
    
matrix1 = np.array(
    [ # 2D
        [1, 2, 3], 
        [4, 5, 6]
    ]
)

matrix2 = np.array(
    [ # 2D
       [-1, -2, -3],
       [-4, -5, -6]
    ]
)

In [36]:
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [37]:
print(matrix2)

[[-1 -2 -3]
 [-4 -5 -6]]


In [38]:
# addition

print( matrix1 + matrix2 )

[[0 0 0]
 [0 0 0]]


In [39]:
# subtraction

print( matrix1 - matrix2 )

[[ 2  4  6]
 [ 8 10 12]]


In [40]:
# multiplication

print( matrix1 * matrix2 )

[[ -1  -4  -9]
 [-16 -25 -36]]


In [41]:
# division

print( matrix1 / matrix2 )

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [54]:
# floor division

print( matrix1 // matrix2)

[[-1 -1 -1]
 [-1 -1 -1]]


# Statistics

In [60]:
print( matrix1 )

[[1 2 3]
 [4 5 6]]


In [61]:
# find the mean 

print( np.mean(matrix1) )

3.5


In [62]:
# find the median

print( np.median(matrix1) )

3.5


In [64]:
# find the maximum value

print( np.max(matrix1) )

6


In [66]:
# find the minimum value

print( np.min(matrix1) )

1


In [65]:
# find the sum of items

print( np.sum(matrix1) )

21


In [67]:
# find the standard deviation

print( np.std(matrix1) )

1.707825127659933


# Pandas DataFrames & Series